"""The Sigma pack ships severities and MITRE ids. Those rot.

`docs/integrations/sigma/agentmetry_rule_*.yml` is generated by
`tools/generate_sigma_pack.py` from the real rule engine. A SOC that imports the
pack routes on the `level` and tags in these files, so a severity that changes
in `rules.py` and not here sends a critical to a low-priority queue and nobody
finds out until an incident.

`test_readme_claims.py` already solves this shape for the corpus counts. This
does the same for the rules a customer actually alerts on.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
import yaml

from agentmetry.core.audit.detection.rules import BUILTIN_RULE_IDS, EXPERIMENTAL_RULE_IDS

SIGMA_DIR = Path(__file__).resolve().parents[3] / "docs" / "integrations" / "sigma"


def _generated() -> dict[tuple[str, str], dict]:
    """Keyed on (rule_id, level).

    One rule id is deliberately two detections: `encoded-command-download` is
    critical for remote code fetched and executed and low for local content
    piped into an interpreter. Those get one Sigma rule each, pinned on
    `action.outcome`, so keying on rule_id alone would silently drop one.
    """
    if not SIGMA_DIR.is_dir():
        pytest.skip(f"sigma pack not found at {SIGMA_DIR}")
    out = {}
    for path in SIGMA_DIR.glob("agentmetry_rule_*.yml"):
        doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        out[(doc["detection"]["selection"]["detection.rule_id"], doc["level"])] = doc
    return out


def _rule_ids(generated) -> set[str]:
    return {rid for rid, _ in generated}


def test_every_builtin_rule_has_a_sigma_rule():
    """A rule with no Sigma rule is invisible to every SIEM that imports the pack."""
    generated = _generated()
    missing = sorted(BUILTIN_RULE_IDS - _rule_ids(generated))
    assert not missing, (
        f"no Sigma rule for: {missing}. Run tools/generate_sigma_pack.py"
    )


def test_no_sigma_rule_for_a_rule_that_does_not_exist():
    """The reverse: a deleted rule leaving a Sigma file that never fires."""
    generated = _generated()
    orphans = sorted(_rule_ids(generated) - BUILTIN_RULE_IDS)
    assert not orphans, (
        f"Sigma rules for ids the engine does not emit: {orphans}. "
        "Delete the file, or the pack promises a detection nobody produces."
    )


def test_severities_match_the_engine():
    """The number a SOC routes on has to be the number the engine emits.

    Harvested the same way the generator harvests it, so this fails when the
    generator has not been re-run after a severity change.
    """
    import json

    from agentmetry.core.audit.detection.benchmark import DEFAULT_CORPUS_DIR
    from agentmetry.core.audit.detection.engine import run_detections, run_host_detections

    generated = _generated()
    for path in sorted(Path(DEFAULT_CORPUS_DIR).glob("*.jsonl")):
        events = [
            json.loads(line)
            for line in path.read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
        for det in (*run_detections(events), *run_host_detections(events)):
            if det.rule_id in EXPERIMENTAL_RULE_IDS:
                # Fires on a synthesised corpus session, but no capture surface
                # a user installs produces the signal it reads. Exporting it
                # would put a rule in a customer's SIEM that can never match.
                continue
            doc = generated.get((det.rule_id, det.severity))
            assert doc is not None, (
                f"{det.rule_id} fires at {det.severity} and no Sigma rule carries that "
                "level. Run tools/generate_sigma_pack.py"
            )


def test_every_rule_is_valid_sigma():
    """Enough of the Sigma shape that an import does not fail on our side."""
    for (rule_id, _level), doc in _generated().items():
        assert doc.get("title", "").startswith("Agentmetry - "), rule_id
        assert doc.get("logsource", {}).get("product") == "agentmetry", rule_id
        assert doc.get("condition") is None, f"{rule_id}: condition belongs under detection"
        assert doc["detection"]["condition"] == "selection", rule_id
        assert doc.get("level") in {"critical", "high", "medium", "low"}, rule_id
        # Sigma requires a UUID and consumers key on it.
        assert re.fullmatch(
            r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
            str(doc.get("id", "")),
        ), f"{rule_id}: id is not a UUID"


def test_rule_ids_are_stable_across_regeneration():
    """Regenerating must not churn every UUID.

    The ids are derived from the rule id rather than randomly, so a consumer who
    pinned a Sigma id keeps working after somebody reruns the generator.
    """
    import hashlib
    import uuid

    generated = _generated()
    counts = {}
    for rid, _ in generated:
        counts[rid] = counts.get(rid, 0) + 1
    for (rule_id, level), doc in generated.items():
        # Severity joins the seed only for a split rule, so unsplit ids never move.
        seed = f"agentmetry.sigma.{rule_id}" + (f".{level}" if counts[rule_id] > 1 else "")
        expected = str(uuid.UUID(bytes=hashlib.sha256(seed.encode()).digest()[:16], version=5))
        assert doc["id"] == expected, (
            f"{rule_id}: id is not the derived one. Regenerating would change it."
        )
